version: '2.9.0'
services:
    frontend:
        container_name: frontend
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
        networks:
            - mynet
        ports:
            - "80:80"
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: bookstore
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        ports:
            - "3306:3306"
        networks:
            - mynet

networks:
  mynet:
